fixtures:
  repositories:
    "puppi": "https://github.com/nholuongut/puppi.git"
    "monitor": "https://github.com/nholuongut/puppet-monitor.git"
    "firewall": "https://github.com/nholuongut/puppet-firewall.git"
    "iptables": "https://github.com/nholuongut/puppet-iptables.git"
    "concat": "https://github.com/nholuongut/puppet-concat.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
  symlinks:
    "apache": "#{source_dir}"

